default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: binary_boardslide_blog_development

test:
  <<: *default
  database: binary_boardslide_blog_test

production:
  <<: *default
  database: binary_boardslide_blog_production
  username: binary_boardslide_blog
  password: <%= ENV["BINARY_BOARDSLIDE_BLOG_DATABASE_PASSWORD"] %>
